# --- Change what appears in the banner and meta data of your pages --- #
title: Camila's teaching tools
description: This is the tag-line of my website.

# --- French --- #
lang: en

# --- List of pages in your site --- #
# --- Only change these if you change the name of your .md files --- #
# --- And, only change the names of the HTML files named after each colon: e.g. page2.html --- #
github:
  page1: index.html
  page2: page2.html
  page3: page3.html
  page4: page4.html
  page5: page5.html
  
# --- List of links in the navigation bar --- #
# --- Change the words after the colons to change your navigation labels --- #
navbar-links:
  page1: Home
  page2: The life of Camila in south of France
  page3: Gastronomy is south of France
  page4: Site sighseeing in south of France
  page5: Camila love for Nature
